# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: 01 - Reforzamiento Build

on:
  push:
    branches: [ "main" ]
    paths:
      - '01-reforzamiento/**'
  workflow_dispatch: # Ejecucion Manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Clonar el repositorio
      - name: Checkout repositorio
        uses: actions/checkout@v4
        
      # Configurar Node Js
      - name: Setup Node Js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Ubicacion
        run: ls "${{ github.workspace }}"
      # Instalar dependencias
      - name: Instalando dependencias
        working-directory: "${{ github.workspace }}/01-reforzamiento"
        run: npm install
      # Compilar proyecto
      - name: Compilar proyecto
        working-directory: "${{ github.workspace }}/01-reforzamiento"
        run: npm run build
      # Copiar el build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./01-reforzamiento/dist   # carpeta de salida del build
          publish_branch: gh-pages    # rama de despliegue
          destination_dir: docs/reforzamiento
      
