# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Clonar el repositorio
      - name: Checkout repositorio
        uses: actions/checkout@v4
        
      # Configurar Node Js
      - name: Setup Node Js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      # Instalar dependencias
      - name: Instalando dependencias
        run: npm install
      # Compilar proyecto
      - name: Compilar proyecto
        working-directory: ./01-reforzamiento
        run: npm run build
      # Copiar el build
      - name: Copy build
        run: |
          mkdir -p docs/reforzamiento
          cp -r 01-reforzamiento/build/* docs/reforzamiento
      
