# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ "main" ]
    paths:
      - '01-reforzamiento/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Clonar el repositorio
      - name: Checkout repositorio
        uses: actions/checkout@v4
        
      # Configurar Node Js
      - name: Setup Node Js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Ubicacion
        run: ls ${{ github.workspace }}
      # Instalar dependencias
      - name: Instalando dependencias
        working-directory: ${{ github.workspace }}/01-reforzamiento
        run: npm install
      # Compilar proyecto
      - name: Compilar proyecto
        working-directory: ${{ github.workspace }}/01-reforzamiento
        run: npm run build
      # Copiar el build
      - name: Copy build
        run: |
          if [ ! -d "${{ github.workspace }}/docs/reforzamiento" ]; then
            echo "Carpeta proyecto1 no existe, creando..."
            mkdir -p $${{ github.workspace }}/docs/reforzamiento
          else
            echo "Carpeta proyecto1 ya existe, no se crea."
          fi
          mkdir -p docs/reforzamiento
          cp -r 01-reforzamiento/build/* docs/reforzamiento/
      
